### ISSUE TITLE
Send expiration notifications not working

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#141]
**Describe the bug**
Send expiration notifications not sending. 
1. The option is ticked/enabled
2. The CRON is set 
3. It did use to work, not sure when it stopped, have only just noticed
4. The SSL Certificate - configuration required and SSL Certificate emails are sending fine
5. General WHMCS mail is sending fine

**To Reproduce**
We receive the expiration notifications direct from GGSSL but there is no mail log in WHMCS for the same SSL for the customer.

**Expected behavior**
Expect to see email sent from WHMCS to the customer with the 'SSLCenter - Service Expiration' email template.

**Additional context**
We are using public $version = '2.1.12' still, as each upgrade attempt in the past left our WHMCS broken and your guys very kindly had to access our system to fix the database. Happy to try and update the module if we could please have someone on standby just in case it breaks again?

Many Thanks :) 
C.

**Comment by vlad-evg** [comment]
Dear C,

most of that errors were fixed, please update to the latest version. Your version is more then 1year old and current release is 
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.4.8

**Comment by vlad-evg** [comment]
Let us know if any issues

**Comment by qhgh** [comment]
Hi, Okay I have now updated. Using 1 customer as an example, there are 12 'Expires Soon' SSL's. 

If I then run the notifier.php file, still no emails are sent. Is this correct?

```
php -q /home/whmcs/public_html/modules/addons/SSLCENTERWHMCS/cron/notifier.php
Notifier completed.
<br />Number of emails send: 0
```

Thanks!
C.

**Comment by qhgh** [comment]
Sure, how may I supply this securely to you?

**Comment by vlad-evg** [comment]
Please send it via ticket from client area with the link to that issue.

**Comment by qhgh** [comment]
Thanks, you should have these shortly!

**Comment by vlad-evg** [comment]
Thank you, received and investigating.

**Comment by vlad-evg** [comment]
Fixed with the new release [2.4.9](https://github.com/gogetssl/whmcs-addon/releases/tag/v2.4.9)

**Comment by qhgh** [comment]
Thanks Vlad,

May I ask what the issue was? I guess it was something with our WHMCS?

Thanks
C

**Comment by qhgh** [comment]
To update... I have today received the emails from GGSSL saying some SSL will expire, but WHMCS did not send the SSL Expire email template to our customers. I even ran the `/home/WHMCS/public_html/modules/addons/SSLCENTERWHMCS/cron/notifier.php` manually;

```
[root@web01 ~]# php -q /home/WHMCS/public_html/modules/addons/SSLCENTERWHMCS/cron/notifier.php
Notifier completed.
<br />Number of emails send: 0
```

It seems this is still not working at the moment. 

Thanks,
C

**Comment by vlad-evg** [comment]
Can you please let us know 1-2 orders that should receive such emails and we would dig with developers

**Comment by qhgh** [comment]
Hi Vlad,

Sure, here is an example;

The mail I got: 

Your Sectigo PositiveSSL Wildcard Certificate for (removed) expires in 30 days!

The SSL order:

SSLCenter API Order ID | 849427
Cron Synchronized | Not synchronized
Comodo Order ID | removed
Configuration Status | Completed
Domain | removed
Order Status | Active
Order Status Description | Valid
Valid From | 2018-10-04
Expires | 2020-10-24

Note it says (Cron Synchronized | Not synchronized) , is this also a issue? 

Thanks,
C

**Comment by qhgh** [comment]
Here is another:

Your Sectigo PositiveSSL Certificate for (removed) expires in 7 days!

SSLCenter API Order ID | 1212629
Cron Synchronized | Not synchronized
Comodo Order ID | removed
Configuration Status | Completed
Domain | removed
Order Status | Active
Order Status Description | Valid
Valid From | 2019-10-01
Expires | 2020-10-01

**Comment by vlad-evg** [comment]
Response by developers:

"In both cases mentioned by the client the email is not sent because the certificates have not been synchronized yet. This cron is responsible for synchronization `0 /1 php -q /home/connectquickhost/public_html/modules/addons/SSLCENTERWHMCS/cron/cron.php`"

**Comment by qhgh** [comment]
Hi Vlad,

I've ran that, but none synced: 

```
[root@web01 ~]# php -q /home/WHMCS/public_html/modules/addons/SSLCENTERWHMCS/cron/cron.php
Synchronization completed.<br />Number of synchronized services: 0
```

Maybe this is the root cause? 

Thanks,
C

**Comment by vlad-evg** [comment]
We implemented the appropriate modifications in your environment, please synchronize the certificates and then check if the email was sent

**Comment by qhgh** [comment]
Hi, 

Seems to be the same issue: 

Synchronization:
```
[root@web01 ~]# php -q /home/WHMCS/public_html/modules/addons/SSLCENTERWHMCS/cron/cron.php
Synchronization completed.<br />Number of synchronized services: 0
```

```
[root@web01 ~]# php -q /home/WHMCS/public_html/modules/addons/SSLCENTERWHMCS/cron/notifier.php
Notifier completed.
<br />Number of emails send: 0
```

Thanks,
C

**Comment by vlad-evg** [comment]
Please check now, I was able to determine that today cron should send an email for these three services

Service #18651 Expire date: 2020-10-01 Days left: 1
Service #18671 Expire date: 2020-09-26 Days left: 3
Service #18731 Expire date: 2020-09-28 Days left: 10

**Comment by qhgh** [comment]
Okay, I have tried again.

Sync:
```
[root@web01 ~]# php -q /home/WHMCS/public_html/modules/addons/SSLCENTERWHMCS/cron/cron.php
Synchronization completed.<br />Number of synchronized services: 0
```

Notify:
```
[root@web01 ~]# php -q /home/WHMCS/public_html/modules/addons/SSLCENTERWHMCS/cron/notifier.php
Notifier completed.
<br />Number of emails send: 3
```

I can confirm WHMCS has sent the emails now.

Is there any feedback as to why our WHMCS keeps having these issues with GGSL plugin? 

Thanks for your help :)
C

**Comment by vlad-evg** [comment]
One of the methods incorrectly assigned the SSL Center API Order ID. It is not only you. Sorry for the issue
